import { AlertTriangle, CheckCircle2 } from "lucide-react";

interface FactorListProps {
  kind: "positive" | "negative";
  factors: string[];
}

/** Factors exactly as returned by the backend's deterministic rules (never generated by an LLM). */
export function FactorList({ kind, factors }: FactorListProps) {
  const positive = kind === "positive";
  const title = positive ? "Positive factors" : "Risk factors";
  const Icon = positive ? CheckCircle2 : AlertTriangle;
  const iconClass = positive ? "text-emerald-600 dark:text-emerald-400" : "text-red-600 dark:text-red-400";

  return (
    <div>
      <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{title}</h3>
      {factors.length === 0 ? (
        <p className="text-sm text-slate-500 dark:text-slate-400">
          {positive ? "No notable positive factors were identified." : "No notable risk factors were identified."}
        </p>
      ) : (
        <ul className="space-y-1.5" aria-label={title}>
          {factors.map((factor) => (
            <li key={factor} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-200">
              <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${iconClass}`} aria-hidden="true" />
              <span>{factor}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
