"""Pydantic models for the Gemini AI analysis (Phase 15).

Two layers:

* `GeminiAnalysisOutput` — exactly what Gemini is asked to return (kept deliberately plain — no
  defaults, no constraints — so it can be handed to the SDK as a structured-output schema).
  Length/emptiness rules are enforced afterwards by `app.ai.validation`.
* `AIAnalysisResponse` — what the API returns. It wraps the explanation with the OFFICIAL Phase 14
  decision snapshot, data-availability, model/prompt versions and cache metadata. The decision in
  this wrapper comes from the Phase 14 engine; Gemini's text only explains it.
"""

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

AI_DISCLAIMER = (
    "AI-generated analysis is for informational purposes only and is not "
    "a guarantee of future performance or financial advice."
)

DecisionValue = Literal["BUY", "HOLD", "SELL"]

#: Modules whose availability is reported to Gemini and to the frontend.
AI_INPUT_MODULES = ("market", "technical", "fundamental", "news", "sentiment", "prediction", "risk", "decision")


class GeminiAnalysisOutput(BaseModel):
    """Structured output requested from Gemini (all fields required)."""

    summary: str
    market_analysis: str
    technical_analysis: str
    fundamental_analysis: str
    sentiment_analysis: str
    prediction_analysis: str
    risk_analysis: str
    decision_explanation: str
    bullish_factors: list[str]
    bearish_factors: list[str]
    key_risks: list[str]
    uncertainties: list[str]
    data_quality: str


class AIAnalysisContent(GeminiAnalysisOutput):
    """The validated explanation as returned to the frontend (adds the server-owned disclaimer)."""

    disclaimer: str = AI_DISCLAIMER


class AIModuleAvailability(BaseModel):
    available: bool
    reason: Optional[str] = None


class AIDecisionSnapshot(BaseModel):
    """The OFFICIAL Phase 14 result this analysis explains (copied from the decision engine, never from Gemini)."""

    decision: Optional[DecisionValue] = None
    status: str
    risk_level: Optional[str] = None
    risk_score: Optional[float] = None
    confidence: Optional[float] = None
    decision_score: Optional[float] = None
    engine_version: str
    generated_at: datetime


class AIAnalysisResponse(BaseModel):
    # `model` / `model_version` are legitimate field names, not pydantic namespace clashes.
    model_config = ConfigDict(protected_namespaces=())

    coin_id: str
    symbol: Optional[str] = None
    kind: Literal["ai_explanation"] = "ai_explanation"
    status: Literal["ready"] = "ready"
    analysis: AIAnalysisContent
    decision_snapshot: AIDecisionSnapshot
    data_availability: dict[str, AIModuleAvailability] = Field(default_factory=dict)
    #: Model id configured for the request (see GEMINI_MODEL / app.config.gemini_config).
    model: str
    #: Version string reported by the API for that model, when it reports one.
    model_version: Optional[str] = None
    prompt_version: str
    source_data_timestamp: datetime
    generated_at: datetime
    expires_at: datetime
    #: True once expires_at has passed.
    is_stale: bool = False
    #: True when the Phase 14 decision changed materially after this explanation was written.
    is_outdated: bool = False
    #: True when this was served from storage rather than generated by this request.
    cached: bool = True
    #: Earliest time a manual regeneration is accepted (cooldown), if one applies.
    next_regeneration_at: Optional[datetime] = None
    disclaimer: str = AI_DISCLAIMER
