/**
 * AI Analysis (Phase 15) types — kept in sync with backend/app/ai/schemas/ai_analysis.py.
 *
 * The AI text only EXPLAINS the platform's own analysis. `decision_snapshot` is the official
 * Phase 14 result copied by the backend; the AI cannot change it.
 */

export type AiDecisionValue = "BUY" | "HOLD" | "SELL";

/** The inputs the explanation is built from (also the keys of `data_availability`). */
export type AiInputModule =
  | "market"
  | "technical"
  | "fundamental"
  | "news"
  | "sentiment"
  | "prediction"
  | "risk"
  | "decision";

export interface AiAnalysisContent {
  summary: string;
  market_analysis: string;
  technical_analysis: string;
  fundamental_analysis: string;
  sentiment_analysis: string;
  prediction_analysis: string;
  risk_analysis: string;
  decision_explanation: string;
  bullish_factors: string[];
  bearish_factors: string[];
  key_risks: string[];
  uncertainties: string[];
  data_quality: string;
  disclaimer: string;
}

export interface AiModuleAvailability {
  available: boolean;
  reason: string | null;
}

export interface AiDecisionSnapshot {
  /** Null when the Phase 14 engine could not produce a decision. */
  decision: AiDecisionValue | null;
  status: string;
  risk_level: string | null;
  risk_score: number | null;
  confidence: number | null;
  decision_score: number | null;
  engine_version: string;
  generated_at: string;
}

export interface AiAnalysisResponse {
  coin_id: string;
  symbol: string | null;
  kind: "ai_explanation";
  status: "ready";
  analysis: AiAnalysisContent;
  decision_snapshot: AiDecisionSnapshot;
  data_availability: Partial<Record<AiInputModule, AiModuleAvailability>>;
  model: string;
  model_version: string | null;
  prompt_version: string;
  source_data_timestamp: string;
  generated_at: string;
  expires_at: string;
  /** expires_at has passed. */
  is_stale: boolean;
  /** The Phase 14 decision changed materially after this explanation was written. */
  is_outdated: boolean;
  /** Served from storage rather than generated by this request. */
  cached: boolean;
  /** Earliest time a manual regeneration is accepted (null when none applies). */
  next_regeneration_at: string | null;
  disclaimer: string;
}
